import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='bg-dark'>
        <div className='container py-5'>
          <p className='constrain mb-3'>
            This is the simplest type of parallax to implement.
          </p>
          <p className='constrain'>
            We pretty much just need a <code>&lt;div&gt;</code> element and use
            CSS <code>background-image</code> and{' '}
            <code>background-attachment: fixed;</code>
          </p>
        </div>

        <Image
          src='/img/g1.jpg'
          alt='Space Port Background'
          height='50vh'
          fixed
          darken
        >
          <h3>That's kinda neat, huh</h3>
        </Image>

        {/* <FillerSection /> */}
      </section>
    </div>
  )
}


const FillerSection = () => {
  const fillAmount = 100
  return (
    <div className={`container py-5 scroll-fill-${fillAmount} d-flex center`}>
      <div>
        <p className='text-muted opacity-10'>Filler Content</p>
        <p className='text-muted opacity-20'>Filler Content</p>
        <p className='text-muted opacity-30'>Filler Content</p>
        <p className='text-muted opacity-60'>Filler Content</p>
        <p className='text-muted opacity-80'>Filler Content</p>
        <p className='text-muted opacity-60'>Filler Content</p>
        <p className='text-muted opacity-30'>Filler Content</p>
        <p className='text-muted opacity-20'>Filler Content</p>
        <p className='text-muted opacity-10'>Filler Content</p>
      </div>
    </div>
  )
}

      export default Home